eureka:
  instance:
    hostname: localhost
spring:
  application:
    name: ORDER_SERVICE
   
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
           
   